import "./globals.scss";
import { Inter } from "next/font/google";
import layoutStyle from "../styles/layout.module.scss";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${layoutStyle.flex_container} ${layoutStyle.body}`}
      >
        <Image
          src="./media/blob-1.svg"
          width={80}
          height={100}
          alt="blob"
          loading="lazy"
          className="mosth-depth-base-image"
        ></Image>
        <Image
          src="./media/rectangle.svg"
          width={80}
          height={100}
          alt="blob second"
          loading="lazy"
          className="mosth-depth-base-image-second"
        ></Image>
        <div className={layoutStyle.glass_body}>{children}</div>
      </body>
    </html>
  );
}
